# Generated by Django 2.0.6 on 2019-05-10 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(choices=[('100lvl', '100 LEVEL'), ('200lvl', '200 LEVEL'), ('300lvl', '300 LEVEL'), ('400lvl', '400 LEVEL'), ('500lvl', '500 LEVEL')], default='100lvl', max_length=40)),
                ('interests', models.CharField(blank=True, max_length=255, null=True)),
                ('depertment', models.CharField(blank=True, max_length=40, null=True)),
                ('date_profile_created', models.DateTimeField(auto_now_add=True)),
                ('date_profile_updated', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to=profiles.models.get_image_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
