# Generated by Django 2.0.6 on 2019-05-07 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('100 LEVEL', '100lvl'), ('200 LEVEL', '200lvl'), ('300 LEVEL', '300lvl'), ('400 LEVEL', '400lvl'), ('500 LEVEL', '500lvl')], default='100lvl', max_length=40)),
                ('interests', models.CharField(blank=True, max_length=40, null=True)),
                ('depertment', models.CharField(blank=True, max_length=40, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
