# Generated by Django 2.0.6 on 2019-05-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.CharField(blank=True, help_text='Seperated by commas e.t.c Music, Maths, Computers', max_length=255, null=True),
        ),
    ]
