# Generated by Django 2.0.6 on 2019-05-10 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='depertment',
            new_name='department',
        ),
    ]
