# Generated by Django 2.0.6 on 2019-05-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20190520_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Short Bio Of Your Self', null=True),
        ),
    ]
