# Generated by Django 2.0.6 on 2019-05-07 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20190507_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_profile_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='date_profile_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
