# Generated by Django 2.0.6 on 2019-05-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20190507_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='image.jpg', upload_to='%Y/%m/%d/<built-in function id>'),
            preserve_default=False,
        ),
    ]
