# Generated by Django 2.0.6 on 2019-05-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(help_text='Feedback Topic', max_length=30),
        ),
    ]
