# Generated by Django 2.0.6 on 2019-05-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20190509_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='subject',
            field=models.CharField(default='subject', max_length=30),
            preserve_default=False,
        ),
    ]
