# Generated by Django 2.0.6 on 2019-05-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20190525_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(help_text='Enter Your Email', max_length=254),
        ),
    ]
