# Generated by Django 2.0.6 on 2019-05-20 16:48

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('upload_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_file_uploaded', models.DateTimeField(auto_now=True)),
                ('date_file_uploaded_updated', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=blog.models.user_directory_path)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
            options={
                'db_table': 'at_file_uploads',
            },
        ),
    ]
